export default {
  x: 3352,
  y: 3804,
  spriteID: 1,
  speed: 200,
  turnForce: 1,
  shootDelay: 500,
  map: {
    tilemap: {
      JSONKey: "ArmyGameMaps",
      image: "battle_map_1",
    },
    layers: {
      ground: "Ground",
      objects: "Objects",
      collision: "Collision",
      entities: "Entities",
    },
  },
  body: {
    radius: 50,
    offsetX: -50,
    offsetY: -50,
  },
  bullet: {
    damage: 10,
    attackRange: 600,
    sprite: "bullet-0",
    speed: 700,
    offset: 60,
    startCount: 15,
    body: {
      width: 12,
      height: 12,
      offsetX: 30,
      offsetY: 30,
    },
    impactAnim: {
      x: 0,
      y: 0,
      sprite: "shoot-impact-sprite-0",
      offset: 30,
      visibleAtStart: false,
    },
  },
  bars: {
    x: 0,
    y: 0,
    health: {
      image: "tank-healthbar",
      containerImage: "tank-health-bar-container",
      max: 3000,
      offsetX: 0,
      offsetY: -130,
    },
    ammoBar: {
      image: "ammo-count-image",
      imageWidth: 17,
      containerImage: "tank-ammo-bar-container",
      resetDelayTime: 1000,
      ammoCount: 10,
      maxAmmo: 10,
      offsetX: -100,
      offsetY: -100,
    },
  },
  energy: {
    sprite: "healthbar",
    max: 100,
    offsetX: 0,
    offsetY: 0,
  },
  shootAnim: {
    x: 0,
    y: 0,
    sprite: "shoot-sprite-0",
    visibleAtStart: false,
    offset: 70,
  },
  explosionAnim: {
    x: 0,
    y: 0,
    sprite: "object-destroy-sprite-0",
    visibleAtStart: false,
    offset: 0,
  },
  gun: {
    rotateSpeed: 0.02,
    offset: 10,
    ease: "Power2",
    duration: 100,
    yoyo: true,
  },
  trackAnim: {
    x: 40,
    y: 0,
    sprite: "track-sprite-0",
    visibleAtStart: true,
  },
};
